# SPDX-FileCopyrightText: 2021-2023 Heiko Schaefer <heiko@schaefer.name>
# SPDX-FileCopyrightText: 2021-2022 Nora Widdecke <mail@nora.pink>
# SPDX-License-Identifier: CC0-1.0

stages:
  - lint
  - test
  - virtual-cards
  - udeps
  - hw-builddeps
  - hw-import
  - hw-keygen

variables:
  CARGO_HOME: cargo/
  CARGO_TERM_VERBOSE: 'true'

cache: &general_cache_config
  # default key is default
  # default policy is pull-push
  paths:
    - target/
    - $CARGO_HOME

.report-rust: &report-rust
  - cargo --version
  - rustc --version

reuse:
  stage: lint
  image:
    name: fsfe/reuse:latest
    entrypoint: [ "" ]
  script:
    - reuse lint
  dependencies: [ ]
  cache: [ ]

cargo-fmt:
  stage: lint
  image: rust:latest
  before_script:
    - export CARGO_HOME="/usr/local/cargo" # HACK: set back to its default
    - rustup toolchain install nightly && rustup component add --toolchain nightly rustfmt
    - *report-rust
  script:
    - cargo +nightly fmt -- --check
  cache: [ ]

cargo-clippy:
  stage: lint
  image: rust:latest
  before_script:
    - mkdir -p /run/user/$UID
    - apt update -y -qq
    - apt install -y -qq --no-install-recommends git clang make pkg-config nettle-dev libssl-dev capnproto ca-certificates libpcsclite-dev
    - apt clean
    - *report-rust
  script:
    - rustup component add clippy
    - cargo clippy --verbose --tests -- -D warnings
  allow_failure: true
  cache:
    # inherit all general cache settings
    <<: *general_cache_config
    # override the key
    key: "rust-latest"

semver-checks:
  stage: lint
  image: rust:latest
  before_script:
    - mkdir -p /run/user/$UID
    - apt update -y -qq
    - apt install -y -qq --no-install-recommends git clang make cmake pkg-config nettle-dev libssl-dev capnproto ca-certificates libpcsclite-dev
    - apt clean
    - *report-rust
  script:
    - cargo install cargo-semver-checks
    - cargo semver-checks -p card-backend -p card-backend-pcsc -p card-backend-scdc -p openpgp-card -p openpgp-card-sequoia
  allow_failure: true
  cache:
    # inherit all general cache settings
    <<: *general_cache_config
    # override the key
    key: "rust-latest"

cargo-deny:
  stage: lint
  image: rust:latest
  before_script:
    # The cargo deny binary is cached, so installing it errors if it was
    # restored from cache. Ignore that error.
    # Clear the cache to force a rebuild.
    - cargo install --locked cargo-deny || true
    - *report-rust
  script:
    - cargo deny check
  cache:
    paths:
      - cargo/bin/cargo-deny
    key: "deny"

udeps:
  stage: udeps
  needs: [ ]
  image: rustlang/rust:nightly-slim
  before_script:
    - mkdir -p /run/user/$UID
    - apt update -y -qq
    - apt install -y -qq --no-install-recommends curl git clang make pkg-config nettle-dev libssl-dev capnproto ca-certificates libpcsclite-dev
    - apt clean
    - cargo install cargo-udeps
  script:
    - cargo udeps --workspace --all-features --all-targets
  cache: [ ]

cargo-test:
  stage: test
  image: rust:latest
  before_script:
    - mkdir -p /run/user/$UID
    - apt update -y -qq
    - apt install -y -qq --no-install-recommends git clang make pkg-config nettle-dev libssl-dev capnproto ca-certificates libpcsclite-dev
    - apt clean
    - *report-rust
  script:
    # there is no virtual card in this image, so subplot does not generate tests
    # that would require one.
    - cargo test
  cache:
    # inherit all general cache settings
    <<: *general_cache_config
    # override the key
    key: "rust-latest"

cargo-test-debian-bookworm:
  stage: test
  image: debian:bookworm-slim
  before_script:
    - mkdir -p /run/user/$UID
    - apt update -y -qq
    - apt install -y -qq --no-install-recommends git rustc cargo clang make pkg-config nettle-dev libssl-dev capnproto ca-certificates libpcsclite-dev
    - apt clean
    - *report-rust
    - cargo update
    - cargo update -p sequoia-openpgp --precise 1.15.0
    - cargo update -p buffered-reader --precise 1.1.5
    - cargo update -p regex --precise 1.9.6
    - cargo update -p lalrpop@0.20.2 --precise 0.19.12 # hack to work with Rust 1.63
    - cargo update -p petgraph --precise 0.6.3 # hack to work with Rust 1.63
  script:
    # there is no virtual card in this image, so subplot does not generate tests
    # that would require one.
    - cargo test
  allow_failure: true
  cache:
    # inherit all general cache settings
    <<: *general_cache_config
    # override the key
    key: "bookworm"
