# SPDX-FileCopyrightText: Heiko Schaefer <heiko@schaefer.name>
# SPDX-License-Identifier: CC0-1.0

[package]
name = "openpgp-card-rpgp"
description = "Companion crate for using openpgp-card with rPGP"
version = "0.0.6"
edition = "2021"
authors = [
    "Wiktor Kwapisiewicz <wiktor@metacode.biz>",
    "Heiko Schaefer <heiko@schaefer.name>",
]
license = "MIT OR Apache-2.0"
repository = "https://codeberg.org/openpgp-card/rpgp"
documentation = "https://docs.rs/openpgp-card-rpgp"

[dependencies]
chrono = "0.4"
openpgp-card = "0.5"
pgp = "0.12.0-alpha.2"
rand = "0.8"
rsa = "0.9"
secrecy = "0.8"
thiserror = "1"

[dev-dependencies]
anyhow = "1"
card-backend-pcsc = "0.5"
card-backend-scdc = "0.5"
env_logger = "0.11"
hex = "0.4"
log = "0.4"
rpgpie = "0.0.12"
serde = { version = "1", features = ["derive"] }
testresult = "0.4"
toml = "0.8"
