[package]
name = "openpgp-card-rpgp"
description = "Companion crate for using openpgp-card with rPGP"
version = "0.0.1"
edition = "2021"
authors = ["Wiktor Kwapisiewicz <wiktor@metacode.biz>", "Heiko Schaefer <heiko@schaefer.name>"]
license = "MIT OR Apache-2.0"
repository = "https://codeberg.org/openpgp-card/rpgp"
documentation = "https://docs.rs/openpgp-card-rpgp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
openpgp-card = "0.4"
pgp = "0.12.0-alpha.1"
rand = "0.8"

[dev-dependencies]
card-backend-pcsc = "0.5"
testresult = "0.4"
