# SPDX-FileCopyrightText: Heiko Schaefer <heiko@schaefer.name>
# SPDX-License-Identifier: MIT OR Apache-2.0

[workspace]
members = ["openpgp-card", "card-backend", "pcsc", "scdc", "rpgp"]

[package]
name = "useful-pgp-agent"
edition = "2021"

[dependencies]
pcsc = "2.8.2"
card-backend-pcsc = { path = "./pcsc" }
openpgp-card = { path = "./openpgp-card" }
openpgp-card-rpgp = { path = "./rpgp" }
thiserror = "2.0.12"
serde = { version = "1.0.218", features = ["derive"] }
serde_yaml = "0.9.34"
lazy_static = "1.5.0"
libc = "0.2.170"
anyhow = "1.0.97"
pgp = "0.15.0"
rpassword = "7.3.1"
secrecy = "0.8"
dirs = "6.0.0"
threadpool = "1.8.1"
