# SPDX-FileCopyrightText: 2021-2023 Heiko Schaefer <heiko@schaefer.name>
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "openpgp-card"
description = "A client implementation for the OpenPGP card specification"
license = "MIT OR Apache-2.0"
version = "0.5.0-alpha.4"
authors = ["Heiko Schaefer <heiko@schaefer.name>"]
edition = "2018"
repository = "https://gitlab.com/openpgp-card/openpgp-card"
documentation = "https://docs.rs/crate/openpgp-card"

[dependencies]
card-backend = { path = "../card-backend", version = "0.2" }
chrono = "0.4"
hex-slice = "0.1"
log = "0.4"
nom = "7"
secrecy = "0.8.0"
sha2 = "0.10"
thiserror = "1"

[dev-dependencies]
hex-literal = "0.4"
