# SPDX-FileCopyrightText: 2021 Heiko Schaefer <heiko@schaefer.name>
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "openpgp-card-scdc"
description = "Experimental SCDaemon Client, intended for use with the openpgp-card crate"
version = "0.0.1"
edition = "2018"

[dependencies]
openpgp-card = { path = "../openpgp-card" }
sequoia-ipc = {  git = "https://gitlab.com/sequoia-pgp/sequoia.git" }
libc = "0.2"
hex = "0.4"
anyhow = "1"
futures = "0.3"
tokio = "0.2"
lazy_static = "1.4"
log = "0.4"